import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

import {
  applySystemBarStyle,
  backgroundTone,
  patchAndroidSystemBars
} from "../../../mobile/system-bars";
import { mainActivityPath, REAL_MAIN_ACTIVITY } from "./fixtures";

/** {@link REAL_MAIN_ACTIVITY} styled for a dark background: light status bar icons. */
const DARK_MAIN_ACTIVITY = [
  "package dev.moku.v6app",
  "",
  "import android.os.Bundle",
  "import androidx.activity.enableEdgeToEdge",
  "import androidx.activity.SystemBarStyle",
  "import android.graphics.Color",
  "",
  "class MainActivity : TauriActivity() {",
  "  override fun onCreate(savedInstanceState: Bundle?) {",
  "    enableEdgeToEdge(statusBarStyle = SystemBarStyle.dark(Color.TRANSPARENT), navigationBarStyle = SystemBarStyle.dark(Color.TRANSPARENT))",
  "    super.onCreate(savedInstanceState)",
  "  }",
  "}",
  ""
].join("\n");

/** {@link REAL_MAIN_ACTIVITY} styled for a light background: dark status bar icons. */
const LIGHT_MAIN_ACTIVITY = [
  "package dev.moku.v6app",
  "",
  "import android.os.Bundle",
  "import androidx.activity.enableEdgeToEdge",
  "import androidx.activity.SystemBarStyle",
  "import android.graphics.Color",
  "",
  "class MainActivity : TauriActivity() {",
  "  override fun onCreate(savedInstanceState: Bundle?) {",
  "    enableEdgeToEdge(statusBarStyle = SystemBarStyle.light(Color.TRANSPARENT, Color.TRANSPARENT), navigationBarStyle = SystemBarStyle.light(Color.TRANSPARENT, Color.TRANSPARENT))",
  "    super.onCreate(savedInstanceState)",
  "  }",
  "}",
  ""
].join("\n");

const ACTIVITY_PATH = "/repo/.moku/tauri/src-tauri/gen/android/app/src/main/java/MainActivity.kt";

/** Writes a MainActivity.kt, creating its package folders. */
const seedActivity = async (filePath: string, content: string) => {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, content, "utf8");
};

/** Converts LF line endings to CRLF. */
const toCrlf = (text: string) => text.replaceAll("\n", "\r\n");

describe("backgroundTone", () => {
  it("reads the intake colour #10161d as dark", () => {
    expect(backgroundTone("#10161d")).toBe("dark");
  });

  it("reads black as dark and white as light", () => {
    expect(backgroundTone("#000000")).toBe("dark");
    expect(backgroundTone("#ffffff")).toBe("light");
  });

  it("ignores the alpha channel", () => {
    expect(backgroundTone("#10161dff")).toBe("dark");
    expect(backgroundTone("#ffffff00")).toBe("light");
  });

  it("splits at relative luminance 0.5", () => {
    // #bbbbbb is ~0.497, #bcbcbc is ~0.503 after the sRGB transfer curve.
    expect(backgroundTone("#bbbbbb")).toBe("dark");
    expect(backgroundTone("#bcbcbc")).toBe("light");
  });

  it("weights the channels like the eye does", () => {
    expect(backgroundTone("#00ff00")).toBe("light");
    expect(backgroundTone("#0000ff")).toBe("dark");
  });

  it("accepts upper-case hex", () => {
    expect(backgroundTone("#FFFFFF")).toBe("light");
  });

  it("refuses a value that is not a hex colour", () => {
    expect(() => backgroundTone("black")).toThrow(
      '[native] app.backgroundColor "black" is not a valid colour.\n  Use a hex colour such as "#10161d".'
    );
  });
});

describe("applySystemBarStyle", () => {
  it("writes light icons and both imports for a dark background", () => {
    expect(applySystemBarStyle(REAL_MAIN_ACTIVITY, "dark", ACTIVITY_PATH)).toBe(DARK_MAIN_ACTIVITY);
  });

  it("writes dark icons and both imports for a light background", () => {
    expect(applySystemBarStyle(REAL_MAIN_ACTIVITY, "light", ACTIVITY_PATH)).toBe(
      LIGHT_MAIN_ACTIVITY
    );
  });

  it("leaves the generated file as it is when the colour is unset", () => {
    expect(applySystemBarStyle(REAL_MAIN_ACTIVITY, undefined, ACTIVITY_PATH)).toBe(
      REAL_MAIN_ACTIVITY
    );
  });

  it("switches a dark rewrite to light without adding imports twice", () => {
    expect(applySystemBarStyle(DARK_MAIN_ACTIVITY, "light", ACTIVITY_PATH)).toBe(
      LIGHT_MAIN_ACTIVITY
    );
  });

  it("restores the generated bytes exactly when the colour is unset again", () => {
    expect(applySystemBarStyle(DARK_MAIN_ACTIVITY, undefined, ACTIVITY_PATH)).toBe(
      REAL_MAIN_ACTIVITY
    );
    expect(applySystemBarStyle(LIGHT_MAIN_ACTIVITY, undefined, ACTIVITY_PATH)).toBe(
      REAL_MAIN_ACTIVITY
    );
  });

  it("is idempotent — a second pass changes nothing", () => {
    expect(applySystemBarStyle(DARK_MAIN_ACTIVITY, "dark", ACTIVITY_PATH)).toBe(DARK_MAIN_ACTIVITY);
    expect(applySystemBarStyle(LIGHT_MAIN_ACTIVITY, "light", ACTIVITY_PATH)).toBe(
      LIGHT_MAIN_ACTIVITY
    );
  });

  it("keeps CRLF line endings on rewrite and on restore", () => {
    const crlf = toCrlf(REAL_MAIN_ACTIVITY);
    const dark = applySystemBarStyle(crlf, "dark", ACTIVITY_PATH);

    expect(dark).toBe(toCrlf(DARK_MAIN_ACTIVITY));
    expect(dark).not.toMatch(/[^\r]\n/);
    expect(applySystemBarStyle(dark, undefined, ACTIVITY_PATH)).toBe(crlf);
  });

  it("keeps an import that other code still uses when restoring", () => {
    const usesColor = REAL_MAIN_ACTIVITY.replace(
      "import androidx.activity.enableEdgeToEdge\n",
      "import androidx.activity.enableEdgeToEdge\nimport android.graphics.Color\n"
    ).replace(
      "    super.onCreate(savedInstanceState)\n",
      "    super.onCreate(savedInstanceState)\n    window.setBackgroundDrawable(ColorDrawable(Color.BLACK))\n"
    );

    const dark = applySystemBarStyle(usesColor, "dark", ACTIVITY_PATH);

    expect(dark.match(/^import android\.graphics\.Color$/gm)).toHaveLength(1);
    expect(applySystemBarStyle(dark, undefined, ACTIVITY_PATH)).toBe(usesColor);
  });

  it("refuses a call it does not recognise when a colour is set", () => {
    const custom = REAL_MAIN_ACTIVITY.replace(
      "enableEdgeToEdge()",
      "enableEdgeToEdge(navigationBarStyle = custom)"
    );

    expect(() => applySystemBarStyle(custom, "dark", ACTIVITY_PATH)).toThrow(
      `[native] The enableEdgeToEdge() call in ${ACTIVITY_PATH} is not the one tauri android init generates.\n  Re-run the mobile init pass (tauri android init) to restore it, or unset app.backgroundColor.`
    );
    expect(applySystemBarStyle(custom, undefined, ACTIVITY_PATH)).toBe(custom);
  });

  it("refuses a file with no import line to add the style imports after", () => {
    const qualified =
      "class MainActivity {\n  fun f() { androidx.activity.enableEdgeToEdge() }\n}\n";

    expect(() => applySystemBarStyle(qualified, "light", ACTIVITY_PATH)).toThrow(
      `[native] The enableEdgeToEdge() call in ${ACTIVITY_PATH} is not the one tauri android init generates.`
    );
  });
});

describe("patchAndroidSystemBars", () => {
  let dir: string;
  let genDir: string;
  let javaDir: string;
  let activityPath: string;

  beforeEach(async () => {
    dir = await mkdtemp(path.join(tmpdir(), "moku-native-system-bars-"));
    genDir = path.join(dir, "src-tauri", "gen", "android");
    javaDir = path.join(genDir, "app", "src", "main", "java");
    activityPath = mainActivityPath(genDir);
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  /** The error for a gen tree without exactly one candidate, given the candidates found. */
  const notOneActivityError = (found: readonly string[]) =>
    found.length === 0
      ? `[native] Could not find the MainActivity.kt that calls enableEdgeToEdge() under ${javaDir}.\n  Re-run the mobile init pass (tauri android init), or unset app.backgroundColor.`
      : `[native] Found ${found.length} MainActivity.kt files that call enableEdgeToEdge() under ${javaDir}: ${found.join(", ")}.\n  Keep the one tauri android init generated, or re-run the mobile init pass (tauri android init).`;

  it("rewrites the generated MainActivity.kt for a dark colour, then reports it unchanged", async () => {
    await seedActivity(activityPath, REAL_MAIN_ACTIVITY);

    const first = await patchAndroidSystemBars(dir, genDir, "#10161d");
    const second = await patchAndroidSystemBars(dir, genDir, "#10161d");

    expect(first).toEqual({ patched: [activityPath], unchanged: [] });
    expect(second).toEqual({ patched: [], unchanged: [activityPath] });
    expect(await readFile(activityPath, "utf8")).toBe(DARK_MAIN_ACTIVITY);
  });

  it("switches to dark icons for a light colour", async () => {
    await seedActivity(activityPath, DARK_MAIN_ACTIVITY);

    await patchAndroidSystemBars(dir, genDir, "#ffffff");

    expect(await readFile(activityPath, "utf8")).toBe(LIGHT_MAIN_ACTIVITY);
  });

  it("restores the generated bytes when the colour is unset", async () => {
    await seedActivity(activityPath, REAL_MAIN_ACTIVITY);
    await patchAndroidSystemBars(dir, genDir, "#10161d");

    const result = await patchAndroidSystemBars(dir, genDir, undefined);

    expect(result).toEqual({ patched: [activityPath], unchanged: [] });
    expect(await readFile(activityPath, "utf8")).toBe(REAL_MAIN_ACTIVITY);
  });

  it("leaves a never-styled MainActivity.kt unchanged when the colour is unset", async () => {
    await seedActivity(activityPath, REAL_MAIN_ACTIVITY);

    const result = await patchAndroidSystemBars(dir, genDir, undefined);

    expect(result).toEqual({ patched: [], unchanged: [activityPath] });
    expect(await readFile(activityPath, "utf8")).toBe(REAL_MAIN_ACTIVITY);
  });

  it("ignores build output and a MainActivity.kt that never calls enableEdgeToEdge", async () => {
    await seedActivity(activityPath, REAL_MAIN_ACTIVITY);
    const buildCopy = path.join(javaDir, "build", "MainActivity.kt");
    const other = path.join(javaDir, "dev", "moku", "other", "MainActivity.kt");
    await seedActivity(buildCopy, REAL_MAIN_ACTIVITY);
    await seedActivity(other, "class MainActivity\n");

    const result = await patchAndroidSystemBars(dir, genDir, "#10161d");

    expect(result).toEqual({ patched: [activityPath], unchanged: [] });
    expect(await readFile(buildCopy, "utf8")).toBe(REAL_MAIN_ACTIVITY);
  });

  it("does nothing without a MainActivity.kt when the colour is unset", async () => {
    await expect(patchAndroidSystemBars(dir, genDir, undefined)).resolves.toEqual({
      patched: [],
      unchanged: []
    });
  });

  it("throws without a MainActivity.kt when a colour is set", async () => {
    await expect(patchAndroidSystemBars(dir, genDir, "#10161d")).rejects.toThrow(
      notOneActivityError([])
    );
  });

  it("throws on two candidates when a colour is set, and leaves both alone when unset", async () => {
    const copy = path.join(javaDir, "dev", "moku", "copy", "MainActivity.kt");
    await seedActivity(activityPath, REAL_MAIN_ACTIVITY);
    await seedActivity(copy, REAL_MAIN_ACTIVITY);

    // Candidates are listed in sorted path order: `copy` sorts before `v6app`.
    await expect(patchAndroidSystemBars(dir, genDir, "#10161d")).rejects.toThrow(
      notOneActivityError([copy, activityPath])
    );
    await expect(patchAndroidSystemBars(dir, genDir, undefined)).resolves.toEqual({
      patched: [],
      unchanged: []
    });
    expect(await readFile(activityPath, "utf8")).toBe(REAL_MAIN_ACTIVITY);
    expect(await readFile(copy, "utf8")).toBe(REAL_MAIN_ACTIVITY);
  });
});
